// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFWd8Sq80QefnP8OTsdSTlnfiIoLRd7L4',
    appId: '1:547675338306:web:78f06b8960968a68d6dfdb',
    messagingSenderId: '547675338306',
    projectId: 'health-app-faa97',
    authDomain: 'health-app-faa97.firebaseapp.com',
    storageBucket: 'health-app-faa97.appspot.com',
    measurementId: 'G-3G70ZXZSXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4Sp5rf9qm5RIv1O3OQInqCUvdMjFY2k',
    appId: '1:547675338306:android:a79541530a97344bd6dfdb',
    messagingSenderId: '547675338306',
    projectId: 'health-app-faa97',
    storageBucket: 'health-app-faa97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbo9lPEJBXHYix_VqKsE6ah6P8IE0FfZU',
    appId: '1:547675338306:ios:6521cd57ed35310fd6dfdb',
    messagingSenderId: '547675338306',
    projectId: 'health-app-faa97',
    storageBucket: 'health-app-faa97.appspot.com',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbo9lPEJBXHYix_VqKsE6ah6P8IE0FfZU',
    appId: '1:547675338306:ios:0615ac47909b38f3d6dfdb',
    messagingSenderId: '547675338306',
    projectId: 'health-app-faa97',
    storageBucket: 'health-app-faa97.appspot.com',
    iosBundleId: 'com.example.healthApp.RunnerTests',
  );
}
